name: "Test"
on:
    - pull_request
    - push

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: "Checkout: local"
              uses: actions/checkout@v4
            - name: "Checkout: mseed3-utils"
              uses: actions/checkout@v4
              with:
                  repository: EarthScope/mseed3-utils
                  path: "mseed3-utils"
            - working-directory: ./mseed3-utils
              run: mkdir build
            - name: "Build mseed3-utils"
              working-directory: ./mseed3-utils/build
              run: cmake ..
            - name: "Install mseed3-utils"
              working-directory: ./mseed3-utils/build
              run: make install
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: "Install Node"
              uses: actions/setup-node@v3
              with:
                  node-version: latest
                  cache: "pnpm"
            - name: "Install Deps"
              run: pnpm install
            - name: "Test"
              run: pnpm run test
