name: "Test"
on:
    - pull_request
    - push

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - name: "Install Node"
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: "Install Deps"
              run: pnpm install
            - name: "Test"
              run: pnpm run test
